In [ ]:
# We are going to create eight related data groups, including one group with a single data point.